export const articles = [
  {
    id: 1,
    title: "Cara Menyimpan Kue Tart Agar Tetap Lembut Berhari-hari",
    link: "/artikel/cara-menyimpan-kue-tart", 
    excerpt: "Pernahkah kamu membeli kue tart yang lezat, namun teksturnya menjadi keras dan kering setelah disimpan di kulkas? Kunci utamanya ada pada cara penyimpanan yang tepat agar kelembapannya terjaga...",
    date: "14 Maret 2026",
    category: "Tips & Trik",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/Strawberry%20Shortcake.webp",
    featured: true,
  },
  {
    id: 2,
    title: "Mengenal Perbedaan Mentega Wisjman dan Margarin Biasa",
    link: "/artikel/mengenal-mentega-wisjman", 
    excerpt: "Banyak yang bertanya, apa rahasia di balik tekstur lumer Nastar Ini Rasa? Jawabannya ada pada pemilihan bahan baku yang tidak kenal kompromi.",
    date: "10 Maret 2026",
    category: "Bahan Premium",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/Nastar%20Wisjman%20Spesial.webp",
    featured: false,
  },
  {
    id: 3,
    title: "5 Alasan Mengapa Hampers Adalah Hadiah Terbaik untuk Kolega",
    link: "/artikel/5-alasan-hampers-terbaik",
    excerpt: "Bukan sekadar bingkisan, hampers adalah representasi dari apresiasi dan rasa hormat. Temukan alasan mengapa hampers selalu menjadi pilihan utama di hari raya.",
    date: "05 Maret 2026",
    category: "Inspirasi",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/medina%20royal.webp",
    featured: false,
  },
  {
    id: 4,
    title: "Di Balik Dapur Ini Rasa: Dedikasi Menjaga Kualitas",
    link: "/artikel/di-balik-dapur-ini-rasa",
    excerpt: "Mengintip rutinitas pagi para baker kami. Dari menimbang tepung hingga memanggang adonan pertama, semuanya dilakukan dengan cinta dan ketelitian.",
    date: "28 Februari 2026",
    category: "Cerita Kami",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/trio%20cake.webp",
    featured: false,
  },
  {
    id: 5,
    title: "Panduan Memilih Hampers yang Tepat Sesuai Anggaran",
    link: "/artikel/panduan-memilih-hampers",
    excerpt: "Bingung memilih hampers yang berkesan tanpa harus menguras kantong? Kami rangkumkan panduan lengkap memilih hampers dari budget hemat hingga premium.",
    date: "20 Mei 2026",
    category: "Panduan",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/shafa.webp",
    featured: false,
  },
  {
    id: 6,
    title: "Kue Ulang Tahun Custom: Cara Pesan dan Apa Saja yang Bisa Dikreasikan",
    link: "/artikel/cara-pesan-kue-custom",
    excerpt: "Ingin kue ulang tahun yang unik dan personal? Dari desain karakter hingga foto edible print, kami jelaskan semua pilihan yang bisa kamu pesan di Ini Rasa.",
    date: "15 Mei 2026",
    category: "Tips & Trik",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/Strawberry%20Shortcake.webp",
    featured: false,
  },
  {
    id: 7,
    title: "Kenapa Kue Buatan Rumah Lebih Sehat dari Kue Pabrik?",
    link: "/artikel/kue-rumahan-vs-pabrik",
    excerpt: "Di balik rasa yang lebih nikmat, kue homemade menyimpan sejumlah keunggulan dari sisi kesehatan. Simak perbandingan komprehensifnya di sini.",
    date: "10 Mei 2026",
    category: "Edukasi",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/cookies.webp",
    featured: false,
  },
  {
    id: 8,
    title: "5 Kreasi Olahan Kue Dubai Cokelat yang Sedang Viral",
    link: "/artikel/tren-kue-dubai-cokelat",
    excerpt: "Kue Dubai Cokelat tengah menjadi buah bibir di media sosial. Dari layer pistachio hingga cokelat belgia, inilah tren rasa yang wajib kamu coba.",
    date: "5 Mei 2026",
    category: "Tren",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/dubai%20cokelat.webp",
    featured: false,
  },
  {
    id: 9,
    title: "Tips Merencanakan Hampers Pernikahan yang Elegan dan Berkesan",
    link: "/artikel/hampers-pernikahan-elegan",
    excerpt: "Hampers pernikahan bukan hanya sekedar souvenir. Ini adalah kesan pertama yang akan selalu diingat tamu undangan Anda. Simak tipsnya di sini.",
    date: "1 Mei 2026",
    category: "Inspirasi",
    image: "https://dwxnfjbdbvulzpzenffk.supabase.co/storage/v1/object/public/ini-rasa/medina%20royal.webp",
    featured: false,
  },
];
